# Generated by Django 3.2.5 on 2021-07-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='activated',
        ),
        migrations.AddField(
            model_name='csv',
            name='csv_file',
            field=models.FileField(null=True, upload_to='csv'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='filename',
            field=models.FileField(max_length=120, upload_to=''),
        ),
    ]
